# Generated by Django 5.2.17 on 2026-09-24 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Performance month must use YYYY-MM.', regex='^\\d{4}-(0[1-9]|1[0-2])$')])),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('GBP', 'GBP'), ('HKD', 'HKD'), ('MYR', 'MYR')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(1e-06), django.core.validators.MaxValueValidator(1000)])),
                ('row_version', models.BigIntegerField(default=1)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ri_fx_rates',
                'ordering': ['-year_month', 'currency'],
                'indexes': [models.Index(fields=['year_month', 'currency'], name='ri_fx_rates_month_idx')],
                'constraints': [models.UniqueConstraint(fields=('year_month', 'currency'), name='ri_fx_rates_month_currency_unique')],
            },
        ),
    ]
