# Generated by Django 5.2.17 on 2026-09-25 06:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxrates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxrate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001')), django.core.validators.MaxValueValidator(Decimal('1000'))]),
        ),
    ]
