# Generated by Django 5.2.17 on 2026-09-26 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_system', models.CharField(max_length=120)),
                ('source_version', models.CharField(blank=True, max_length=120, null=True)),
                ('source_hash', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('source_counts', models.JSONField(default=dict)),
                ('target_counts', models.JSONField(default=dict)),
                ('control_totals', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ri_data_migration_batches',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('dry_run', 'approved', 'completed', 'failed'))), name='ri_data_migration_batches_status')],
            },
        ),
        migrations.CreateModel(
            name='MigrationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=80)),
                ('source_key', models.CharField(max_length=160)),
                ('target_table', models.CharField(blank=True, max_length=80, null=True)),
                ('target_key', models.CharField(blank=True, max_length=160, null=True)),
                ('source_hash', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('issue', models.TextField(blank=True, null=True)),
                ('source_summary', models.JSONField(default=dict)),
                ('target_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='conversion.migrationbatch')),
            ],
            options={
                'db_table': 'ri_data_migration_items',
                'indexes': [models.Index(fields=['batch', 'status', 'entity_type'], name='ri_dm_items_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('validated', 'converted', 'reconciled', 'excluded', 'error'))), name='ri_data_migration_items_status'), models.UniqueConstraint(fields=('batch', 'entity_type', 'source_key'), name='ri_data_migration_items_unique')],
            },
        ),
    ]
