# Generated by Django 5.2.17 on 2026-09-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('ae', 'AE'), ('reinsurer', 'Reinsurer'), ('reinsured', 'Reinsured'), ('class', 'Class'), ('foreign_broker', 'Foreign RI Broker'), ('clause', 'Clause')], max_length=40)),
                ('code', models.CharField(blank=True, max_length=80, null=True)),
                ('name', models.CharField(max_length=240)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('row_version', models.BigIntegerField(default=1)),
                ('created_by', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_by', models.CharField(blank=True, max_length=120, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ri_master_records',
                'indexes': [models.Index(fields=['entity_type', 'is_active'], name='ri_master_r_entity__e81e05_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'code'), name='ri_master_records_type_code_unique')],
            },
        ),
    ]
