# Generated by Django 5.2.17 on 2026-09-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='masterrecord',
            constraint=models.UniqueConstraint(fields=('entity_type', 'name'), name='ri_master_records_type_name_unique'),
        ),
    ]
