# Generated by Django 5.2.17 on 2026-09-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(max_length=20)),
                ('period_key', models.CharField(max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ri_dashboard_targets',
                'indexes': [models.Index(fields=['-period_key', 'period_type'], name='ri_dash_targets_period_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_type__in', ('annual', 'monthly'))), name='ri_dashboard_targets_type_check'), models.CheckConstraint(condition=models.Q(models.Q(('period_key__regex', '^[0-9]{4}$'), ('period_type', 'annual')), models.Q(('period_key__regex', '^[0-9]{4}-(0[1-9]|1[0-2])$'), ('period_type', 'monthly')), _connector='OR'), name='ri_dashboard_targets_key_check'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ri_dashboard_targets_amount_check'), models.CheckConstraint(condition=models.Q(models.Q(('deactivated_at__isnull', True), ('deactivated_by__isnull', True), ('is_active', True)), models.Q(('deactivated_at__isnull', False), ('deactivated_by__isnull', False), ('is_active', False)), _connector='OR'), name='ri_dashboard_targets_lifecycle_check'), models.UniqueConstraint(fields=('period_type', 'period_key'), name='ri_dashboard_targets_period_unique')],
            },
        ),
    ]
