# Generated by Django 5.2.17 on 2026-09-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(choices=[('business_1', 'Business 1'), ('business_2', 'Business 2'), ('special_risk', 'Special Risk'), ('reinsurance', 'Reinsurance'), ('finance', 'Finance'), ('admin', 'Admin'), ('business_development', 'Business Development')], max_length=40)),
                ('role_code', models.CharField(choices=[('sales', 'Sales'), ('accounting', 'Accounting'), ('accounting_manager', 'Accounting Manager'), ('general_manager', 'General Manager'), ('admin', 'Admin'), ('viewer', 'Viewer')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('is_split_eligible', models.BooleanField(default=True)),
                ('account_status', models.CharField(choices=[('not_configured', 'Not configured'), ('pending', 'Pending'), ('active', 'Active'), ('disabled', 'Disabled')], default='not_configured', max_length=20)),
                ('supervisor_name', models.CharField(blank=True, max_length=120, null=True)),
                ('supervisor_email', models.CharField(blank=True, max_length=254, null=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('created_by', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_by', models.CharField(blank=True, max_length=120, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('auth_user_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('account_invited_by', models.CharField(blank=True, max_length=120, null=True)),
                ('account_invited_at', models.DateTimeField(blank=True, null=True)),
                ('account_activated_at', models.DateTimeField(blank=True, null=True)),
                ('account_disabled_by', models.CharField(blank=True, max_length=120, null=True)),
                ('account_disabled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ri_personnel',
                'indexes': [models.Index(fields=['is_active', 'is_split_eligible'], name='ri_personnel_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'department'), name='ri_personnel_name_department_unique'), models.UniqueConstraint(fields=('email',), name='ri_personnel_email_unique'), models.CheckConstraint(condition=models.Q(('department__in', ['business_1', 'business_2', 'special_risk', 'reinsurance', 'finance', 'admin', 'business_development'])), name='ri_personnel_department_check'), models.CheckConstraint(condition=models.Q(('role_code__in', ['sales', 'accounting', 'accounting_manager', 'general_manager', 'admin', 'viewer'])), name='ri_personnel_role_check'), models.CheckConstraint(condition=models.Q(('account_status__in', ['not_configured', 'pending', 'active', 'disabled'])), name='ri_personnel_account_status_check'), models.CheckConstraint(condition=models.Q(models.Q(('deactivated_at__isnull', True), ('deactivated_by__isnull', True), ('is_active', True)), models.Q(('deactivated_at__isnull', False), ('deactivated_by__isnull', False), ('is_active', False)), _connector='OR'), name='ri_personnel_lifecycle_check')],
            },
        ),
    ]
