# Generated by Django 5.2.17 on 2026-09-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
