# Generated by Django 5.2.17 on 2026-09-26 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_draftrecyclebin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_date', models.DateField()),
                ('alert_kind', models.CharField(max_length=40)),
                ('schedule_keys', models.JSONField(default=list)),
                ('recipients', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.PROTECT, related_name='payment_alerts', to='cases.case')),
            ],
            options={
                'db_table': 'ri_payment_alerts',
                'indexes': [models.Index(fields=['case', '-alert_date'], name='ri_payment_alerts_case_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'sent', 'simulated', 'suppressed', 'failed'))), name='ri_payment_alerts_status_check'), models.UniqueConstraint(fields=('case', 'alert_date', 'alert_kind'), name='ri_payment_alerts_case_date_kind_unique')],
            },
        ),
        migrations.CreateModel(
            name='SignedSlipAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_on', models.DateField()),
                ('policy_from', models.DateField()),
                ('days_since_effective', models.IntegerField()),
                ('missing_reinsurers', models.JSONField(default=list)),
                ('recipients', models.JSONField(default=list)),
                ('status', models.CharField(max_length=20)),
                ('message_id', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.PROTECT, related_name='signed_slip_alerts', to='cases.case')),
            ],
            options={
                'db_table': 'ri_signed_slip_alerts',
                'indexes': [models.Index(fields=['case', '-alert_on'], name='ri_signed_slip_alerts_case_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('days_since_effective__gte', 60)), name='ri_signed_slip_alerts_days_check'), models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'sent', 'simulated', 'suppressed', 'failed'))), name='ri_signed_slip_alerts_status_check'), models.UniqueConstraint(fields=('case', 'alert_on'), name='ri_signed_slip_alerts_case_date_unique')],
            },
        ),
    ]
