# Generated by Django 5.2.17 on 2026-09-24 13:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('legacy_case_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('tw_ref', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('case_kind', models.CharField(choices=[('original', 'Original'), ('endorsement', 'Endorsement'), ('renewal', 'Renewal')], default='original', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('closed', 'Closed'), ('reversed', 'Reversed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('reinsurance_structure', models.CharField(blank=True, choices=[('FACULTATIVE', 'Facultative'), ('QS', 'Quota Share'), ('XOL', 'Excess of Loss'), ('TREATY', 'Treaty')], max_length=20, null=True)),
                ('class_code_snapshot', models.CharField(blank=True, max_length=80, null=True)),
                ('class_name_snapshot', models.CharField(blank=True, max_length=240, null=True)),
                ('reinsured_name_snapshot', models.CharField(blank=True, max_length=240, null=True)),
                ('ae_name_snapshot', models.CharField(blank=True, max_length=240, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('row_version', models.BigIntegerField(default=1)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(blank=True, max_length=120, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('recycled_by', models.CharField(blank=True, max_length=120, null=True)),
                ('recycled_at', models.DateTimeField(blank=True, null=True)),
                ('announced_by', models.CharField(blank=True, max_length=120, null=True)),
                ('announced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ae_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.masterrecord')),
                ('class_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.masterrecord')),
                ('owner_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='personnel.personnel')),
                ('parent_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_cases', to='cases.case')),
                ('reinsured_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.masterrecord')),
            ],
            options={
                'db_table': 'ri_cases',
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('offer', 'Offer'), ('signed', 'Signed'), ('confirmation', 'Confirmation')], max_length=20)),
                ('reinsurers', models.JSONField(blank=True, default=list)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('byte_size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('is_selected', models.BooleanField(default=True)),
                ('uploaded_by', models.CharField(max_length=120)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='cases.case')),
            ],
            options={
                'db_table': 'ri_case_documents',
            },
        ),
        migrations.CreateModel(
            name='ReferenceSequence',
            fields=[
                ('prefix', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ri_reference_sequences',
                'constraints': [models.CheckConstraint(condition=models.Q(('last_value__gt', 0)), name='ri_reference_sequences_last_value_check')],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['owner_personnel'], name='ri_cases_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('case_kind__in', ['original', 'endorsement', 'renewal'])), name='ri_cases_case_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'posted', 'closed', 'reversed', 'archived'])), name='ri_cases_status_check'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('reinsurance_structure__isnull', True), ('reinsurance_structure__in', ['FACULTATIVE', 'QS', 'XOL', 'TREATY']), _connector='OR'), name='ri_cases_reinsurance_structure_check'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('row_version__gt', 0)), name='ri_cases_row_version_check'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('effective_date__isnull', True), ('expiration_date__isnull', True), ('expiration_date__gte', models.F('effective_date')), _connector='OR'), name='ri_cases_policy_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('archived_by__isnull', True), ('is_archived', False)), models.Q(('archived_at__isnull', False), ('archived_by__isnull', False), ('is_archived', True)), _connector='OR'), name='ri_cases_archive_consistent'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('recycled_at__isnull', True), ('status', 'draft'), _connector='OR'), name='ri_cases_recycle_draft_only'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['case', 'uploaded_at', 'id'], name='ri_case_documents_case_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='casedocument',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['offer', 'signed', 'confirmation'])), name='ri_case_documents_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='casedocument',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gt', 0), ('byte_size__lte', 5242880)), name='ri_case_documents_byte_size_check'),
        ),
    ]
