# Generated by Django 5.2.17 on 2026-09-26 05:42

import django.db.models.deletion
import django.db.models.functions.comparison
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_draftrecyclebin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('year_month', models.CharField(max_length=7)),
                ('version', models.IntegerField()),
                ('status', models.CharField(choices=[('valid', 'valid'), ('invalid', 'invalid'), ('closed', 'closed'), ('failed', 'failed')], default='valid', max_length=16)),
                ('rows', models.JSONField(default=list)),
                ('excluded_rows', models.JSONField(default=list)),
                ('source_signature', models.TextField()),
                ('row_version', models.BigIntegerField(default=1)),
                ('close_token', models.UUIDField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ri_production_reports',
                'indexes': [models.Index(fields=['-year_month', '-version'], name='ri_prod_reports_month_ver_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('year_month__regex', '^[0-9]{4}-(0[1-9]|1[0-2])$')), name='ri_production_reports_month_format'), models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='ri_production_reports_version_positive'), models.CheckConstraint(condition=models.Q(('status__in', ('valid', 'invalid', 'closed', 'failed'))), name='ri_production_reports_status_check'), models.UniqueConstraint(fields=('year_month', 'version'), name='ri_production_reports_month_version_unique'), models.CheckConstraint(condition=models.Q(models.Q(('close_token__isnull', False), ('closed_at__isnull', False), ('closed_by__isnull', False), ('status', 'closed')), models.Q(models.Q(('status', 'closed'), _negated=True), ('close_token__isnull', True), ('closed_at__isnull', True), ('closed_by__isnull', True)), _connector='OR'), name='ri_production_reports_close_fields'), models.UniqueConstraint(models.Case(models.When(status='closed', then=models.F('year_month'))), name='ri_production_reports_one_closed_month')],
            },
        ),
        migrations.CreateModel(
            name='ProductionExclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_month', models.CharField(max_length=7)),
                ('scope', models.CharField(max_length=16)),
                ('installment_key', models.CharField(max_length=255)),
                ('reinsurer_key', models.CharField(blank=True, max_length=255, null=True)),
                ('deferred_to', models.CharField(max_length=7)),
                ('reason', models.TextField()),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cases.case')),
            ],
            options={
                'db_table': 'ri_production_exclusions',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['deferred_to', 'case'], name='ri_prod_excl_deferred_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('year_month__regex', '^[0-9]{4}-(0[1-9]|1[0-2])$')), name='ri_production_exclusions_month_format'), models.CheckConstraint(condition=models.Q(('deferred_to__regex', '^[0-9]{4}-(0[1-9]|1[0-2])$')), name='ri_production_exclusions_deferred_format'), models.CheckConstraint(condition=models.Q(models.Q(('reinsurer_key__isnull', True), ('scope', 'case')), models.Q(('reinsurer_key__isnull', False), ('scope', 'reinsurer')), _connector='OR'), name='ri_production_exclusions_scope_check'), models.UniqueConstraint(models.F('case'), models.F('year_month'), models.F('scope'), models.F('installment_key'), django.db.models.functions.comparison.Coalesce(models.F('reinsurer_key'), models.Value('')), name='ri_production_exclusions_target_unique')],
            },
        ),
    ]
