# Generated by Django 5.2.17 on 2026-09-25 06:44

import django.core.serializers.json
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=80)),
                ('before_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('after_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('actor_id', models.CharField(max_length=120)),
                ('actor_name', models.CharField(blank=True, max_length=120, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=40, null=True)),
                ('request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(default='application', max_length=40)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retention_until', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'ri_audit_log',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='ri_audit_entity_idx'), models.Index(fields=['occurred_at'], name='ri_audit_occurred_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('before_data__isnull', False), ('after_data__isnull', False), _connector='OR'), name='ri_audit_log_has_change')],
            },
        ),
        migrations.CreateModel(
            name='EntitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=120)),
                ('entity_version', models.BigIntegerField()),
                ('snapshot_reason', models.CharField(max_length=80)),
                ('snapshot_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_by', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ri_entity_snapshots',
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'entity_id', 'entity_version'), name='ri_entity_snapshots_version_unique'), models.CheckConstraint(condition=models.Q(('entity_version__gt', 0)), name='ri_entity_snapshots_version_check')],
            },
        ),
    ]
